### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by Xayom** [HeaTTheatR/DemoKivyContacts#1]
как исправить?
Traceback (most recent call last):
  File "C:/Users/Хайём/PycharmProjects/DemoKivyContacts-master/main.py", line 51, in main
    app = Program()
  File "C:\Users\Хайём\PycharmProjects\DemoKivyContacts-master\program.py", line 56, in __init__
    self.load_all_kv_files()
  File "C:\Users\Хайём\PycharmProjects\DemoKivyContacts-master\program.py", line 180, in load_all_kv_files
    Builder.load_file('{}/{}'.format(directory_kv_files, kv_files))
  File "C:\Python34\lib\site-packages\kivy\lang.py", line 1831, in load_file
    data = fd.read()
  File "C:\Python34\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 1193: character maps to <undefined>

**Comment by HeaTTheatR** [comment]
Посмотрите, какой именно kv файл не хочет загружать...

`    def load_all_kv_files(self):
        directory_kv_files = '{}/libs/uix/kv'.format(self.directory)

        for kv_files in os.listdir(directory_kv_files):
            #############
            print(kv_files)  #
            #############
            if kv_files == 'bugreporter.kv':
                continue
            Builder.load_file('{}/{}'.format(directory_kv_files, kv_files))`

**Comment by Xayom** [comment]
Не смог узнать какой именно kv файл не хочет загружать... (

**Comment by HeaTTheatR** [comment]
А что происходит, где ошибки?
